#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : zope.testrunner
Version  : 5.4.0
Release  : 55
URL      : https://files.pythonhosted.org/packages/6c/fd/a63c8430fae1b4b6f978561d1df65684bf3c22d0e69db00b415ab5754c3d/zope.testrunner-5.4.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/6c/fd/a63c8430fae1b4b6f978561d1df65684bf3c22d0e69db00b415ab5754c3d/zope.testrunner-5.4.0.tar.gz
Summary  : Zope testrunner script.
Group    : Development/Tools
License  : ZPL-2.1
Requires: zope.testrunner-bin = %{version}-%{release}
Requires: zope.testrunner-license = %{version}-%{release}
Requires: zope.testrunner-python = %{version}-%{release}
Requires: zope.testrunner-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pypi(python_subunit)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(six)
BuildRequires : pypi(sphinx)
BuildRequires : pypi(sphinxcontrib_programoutput)
BuildRequires : pypi(testtools)
BuildRequires : pypi(zope.exceptions)
BuildRequires : pypi(zope.interface)
BuildRequires : pypi(zope.testing)
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
zope.testrunner
        =================

%package bin
Summary: bin components for the zope.testrunner package.
Group: Binaries
Requires: zope.testrunner-license = %{version}-%{release}

%description bin
bin components for the zope.testrunner package.


%package license
Summary: license components for the zope.testrunner package.
Group: Default

%description license
license components for the zope.testrunner package.


%package python
Summary: python components for the zope.testrunner package.
Group: Default
Requires: zope.testrunner-python3 = %{version}-%{release}

%description python
python components for the zope.testrunner package.


%package python3
Summary: python3 components for the zope.testrunner package.
Group: Default
Requires: python3-core
Provides: pypi(zope.testrunner)
Requires: pypi(python_subunit)
Requires: pypi(setuptools)
Requires: pypi(six)
Requires: pypi(sphinx)
Requires: pypi(sphinxcontrib_programoutput)
Requires: pypi(testtools)
Requires: pypi(zope.exceptions)
Requires: pypi(zope.interface)
Requires: pypi(zope.testing)

%description python3
python3 components for the zope.testrunner package.


%prep
%setup -q -n zope.testrunner-5.4.0
cd %{_builddir}/zope.testrunner-5.4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1637338477
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/zope.testrunner
cp %{_builddir}/zope.testrunner-5.4.0/LICENSE.md %{buildroot}/usr/share/package-licenses/zope.testrunner/a0b53f43aab58b46bf79ba756c50771c605ab4c5
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/zope-testrunner

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/zope.testrunner/a0b53f43aab58b46bf79ba756c50771c605ab4c5

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
